use spring-batch-test;

select * from BATCH_JOB_INSTANCE;

select * from BATCH_JOB_EXECUTION;
select * from BATCH_JOB_EXECUTION left outer join BATCH_JOB_EXECUTION_PARAMS on BATCH_JOB_EXECUTION.JOB_EXECUTION_ID = BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID order by BATCH_JOB_EXECUTION.JOB_EXECUTION_ID asc;